name: update on push CICD react-native

# Controls when the action will run.
on:
  # Triggers the workflow on push on main branch
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  install-and-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      # Checks-out repository to allow the job to access it
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: npm install
  build-android:
    needs: install-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: npm install
        # Build our android app to get an apk
      - name: Build Android Release
        run: cd android && ./gradlew assembleRelease
        # Upload our apk
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/
        # Deploying apk to server
      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          key: ${{ secrets.PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          rm: true
          source: "android/app/build/outputs/apk/release/"
          target: "/home/pierre/mobile"
